### PR TITLE
no-import-all-from-library rule example

### PR DESCRIPTION
**Pull request by JuBaas**
The aim of this PR is to add an example for no-import-all-from-library sonar rule

### CODE REVIEW

**Comment by utarwyn** [comment]
@JuBaas Did you push the full test case? I only see the non-compliant import

**Comment by JuBaas** [comment]
I think that what we said at the challenge... but do you want me to add the compliant one too?

**Comment by utarwyn** [comment]
Yes why not, it would be great to have both cases

**Comment by JuBaas** [comment]
I just pushed it 👌

**Review by utarwyn — APPROVED** [review]

**Pull request merged**
